Introduce yarn and webpack
vertinha/ahgora-vai pull request #2
Opened 2019-01-30 01:56 UTC by ravishi

2019-01-31 18:32 UTC, vertinha requested changes
É esse o 🇧🇷 que eu quero

2019-01-31 18:32 UTC, vertinha commented on src/background.html
> +<!DOCTYPE html>
Nao precisamos por agora desse arquivo, certo?

2019-01-31 18:32 UTC, vertinha commented on src/js/background.js
> +import '../img/icon-128.png'
Qual o proposito aqui dos imports? 🤔

2019-01-31 18:32 UTC, vertinha commented on src/js/options.js
> +import "../css/options.css";
+1 arquivo desnecessario, tu ja tinha falado que ia fazer a limpa né

2019-01-31 18:32 UTC, vertinha commented on src/options.html
> +<html lang="en">
+1

2019-01-31 18:32 UTC, vertinha commented on utils/env.js
> +  PORT: (process.env.PORT || 3000)
Eita, porta?

2019-01-31 18:32 UTC, vertinha commented on utils/webserver.js
> +var WebpackDevServer = require("webpack-dev-server"),
Webserver tambem parece nao ser necessario pra gente, ou temos algum ganho? Se é que é possivel executar 🤔

2019-01-31 19:49 UTC, ravishi commented on utils/webserver.js
> +var WebpackDevServer = require("webpack-dev-server"),
Creio que o webserver e a porta servem pra fazer hot-reload nas páginas de opção e background, que já identificamos que não vamos precisar. Vou remover tudo!

2019-01-31 19:51 UTC, ravishi commented on src/js/background.js
> +import '../img/icon-128.png'
Esses ícones só são referenciados no manifest, que não é interpretado pelo Webpack. Sendo assim, o Webpack não tem como saber que tem que "copiar" esses arquivos pra pasta de build. Daí fazem esse hack de importar eles num lugar pro Webpack saber que tem que copiar eles.

Pensando bem a respeito, deve ter uma maneira de configurar um CopyPlugin no webpack.config.js pra fazer isso e deixar mais explícita a intenção desses caras.

2019-03-08 17:37 UTC, ravishi commented on src/background.html
> +<!DOCTYPE html>
Tirado!

2019-03-08 17:37 UTC, ravishi commented on src/js/options.js
> +import "../css/options.css";
Hecho!

2019-03-08 17:37 UTC, ravishi commented on src/options.html
> +<html lang="en">
-1

2019-03-08 17:38 UTC, ravishi commented on utils/env.js
> +  PORT: (process.env.PORT || 3000)
Removi todas as porta!

2019-03-08 17:38 UTC, ravishi commented on utils/webserver.js
> +var WebpackDevServer = require("webpack-dev-server"),
▶️ 🗑

2019-03-08 17:49 UTC, ravishi commented on src/js/background.js
> +import '../img/icon-128.png'
Done!

2019-03-15 18:10 UTC, closed without merging